// src/vue/components/LoginDialog/index.vue
<script setup lang="ts">
import { useLoginStore } from '@/vue/stores/login'
import { ElMessage } from 'element-plus'
import { watch, onUnmounted, onMounted, ref } from 'vue'
import { isMobileDevice } from "@/utils/utils.ts";

const model = defineModel<boolean>()
const loginStore = useLoginStore()
const emits = defineEmits<{
  (e: 'login-success'): void
  (e: 'login-failed'): void
}>()

const iframeUrl = 'https://www.baowenmao.com/login/login'
const allowedOrigin = 'https://www.baowenmao.com'
const iframeRef = ref<HTMLIFrameElement | null>(null)
const iframeLoadFailed = ref(false)
const loadTimeout = ref<NodeJS.Timeout | null>(null)
const isMobile = ref<boolean>(isMobileDevice())

// 处理来自 iframe 的 postMessage 事件
const handleMessage = async (event: MessageEvent) => {
  // 验证消息来源，确保安全性
  console.log(event)

  if (event.origin !== allowedOrigin) {
    console.log('收到来自未授权源的消息:', event.origin)
    return
  }
  if (!event.data?.action) {
    return
  }

  try {
    const data = typeof event.data === 'string' ? JSON.parse(event.data) : event.data

    // 根据消息类型处理不同的事件
    if (data?.action === 'ticketSend' && data?.data?.ticket) {
      const ticket = data?.data?.ticket
      const req = await loginStore.loginWithTicket(ticket)
      if (req?.success) {
        // showLoginDialog 中的 handleLoginSuccess 会处理对话框关闭和清理
        await loginStore.initUserInfo
        emits('login-success')
      } else {
        emits('login-failed')
      }
    }
    // 可以添加更多消息类型的处理
  } catch (error) {
    emits('login-failed')
    window.removeEventListener('message', handleMessage)
    console.error('解析 postMessage 数据失败:', error)
  }
}

onUnmounted(() => {
  // 移除 postMessage 监听器
  window.removeEventListener('message', handleMessage)
  // 清理超时定时器
  if (loadTimeout.value) {
    clearTimeout(loadTimeout.value)
    loadTimeout.value = null
  }
})

// 处理 iframe 加载成功
const handleIframeLoad = () => {
  if (loadTimeout.value) {
    clearTimeout(loadTimeout.value)
    loadTimeout.value = null
  }
  iframeLoadFailed.value = false
}

// 处理 iframe 加载失败
const handleIframeError = () => {
  iframeLoadFailed.value = true
  if (loadTimeout.value) {
    clearTimeout(loadTimeout.value)
    loadTimeout.value = null
  }
}

watch(model, (newVal) => {
  if (newVal) {
    isMobile.value = isMobileDevice()
    window.addEventListener('message', handleMessage)
    iframeLoadFailed.value = false

    // 设置超时检测（5秒后如果还没加载成功，显示兜底）
    loadTimeout.value = setTimeout(() => {
      if (iframeRef.value) {
        try {
          // 尝试访问 iframe 内容来判断是否加载成功
          const iframeDoc = iframeRef.value.contentDocument || iframeRef.value.contentWindow?.document
          if (!iframeDoc || !iframeDoc.body || iframeDoc.body.children.length === 0) {
            iframeLoadFailed.value = true
          }
        } catch (e) {
          // 跨域情况下无法访问，假设加载失败
          iframeLoadFailed.value = true
        }
      }
    }, 5000)
  } else {
    window.removeEventListener('message', handleMessage)
    if (loadTimeout.value) {
      clearTimeout(loadTimeout.value)
      loadTimeout.value = null
    }
  }
}, { immediate: true })

</script>

<template>
  <el-dialog
    v-model="model"
    :close-on-click-modal="false"
    :close-on-press-escape="false"
    :show-close="false"
    :class="{
      'login-dialog': true,
      'mobile': isMobile,
    }"
  >
    <div
      :class="{
        'w-100 h-140 relative overflow-hidden': true,
        'w-full! h-230!': isMobile
      }"
      v-loading="iframeLoadFailed"
    >
      <div class="flex flex-row-reverse">
        <div
          class="iconfont text-[32px]! w-10 h-10 leading-10 text-center rounded-md active:bg-[#e5e5e5] cursor-pointer"
          @click="model = false">&#xe633;
        </div>
      </div>
      <iframe
        v-if="!iframeLoadFailed"
        ref="iframeRef"
        :src="iframeUrl"
        sandbox="allow-same-origin allow-scripts allow-popups allow-forms"
        allow="camera; microphone"
        class="login-iframe w-full h-full"
        @load="handleIframeLoad"
        @error="handleIframeError"
      ></iframe>
      <!-- 兜底内容 -->
      <div
        v-else
        class="w-full h-full flex flex-col items-center justify-center bg-gray-50 border border-gray-200 rounded"
      >
        <div class="text-gray-500 text-center px-4">
          <div class="text-lg mb-2">无法加载登录页面</div>
          <div class="text-sm mb-4">请检查网络连接或稍后重试</div>
          <button
            @click="iframeLoadFailed = false"
            class="px-4 py-2 bg-blue-500 text-white rounded hover:bg-blue-600"
          >
            重新加载
          </button>
        </div>
      </div>
    </div>
  </el-dialog>
</template>

<style lang="less">
.login-dialog.el-dialog {
  --el-dialog-width: calc(400px + 32px * 2) !important;

  .el-dialog__header {
    display: none;
  }

  .el-dialog__body {
    display: flex;
    justify-content: center;
  }

  &.mobile {
    padding: 16px !important;
    --el-dialog-width: 650px !important;

    .el-dialog__headerbtn {
      right: 24px;
      top: 24px;
    }

    .el-icon.el-dialog__close {
      width: 40px;
      height: 40px;

      svg {
        width: 40px;
        height: 40px;
      }
    }
  }
}
</style>

// src/components/LoginDialog/LoginDialog.tsx
import * as React from 'react'
import { useCallback, useEffect, useRef, useState } from 'react'
import { Dialog, DialogContent, DialogTitle, VisuallyHidden } from '@/components/ui/Dialog'
import { useLoginStore } from '@/stores/loginStore'
import { isMobileDevice } from '@/utils/isMobileDevice'
import { toast } from "sonner";
import { cn } from '@/lib/utils'
import { Button } from "@/components/ui/Button.tsx";

const IFRAME_URL_VX = 'https://www.baowenmao.com/login/login?wxLogin=1'
const IFRAME_URL = 'https://www.baowenmao.com/login/login'
const ALLOWED_ORIGIN = 'https://www.baowenmao.com'
const LOAD_TIMEOUT_MS = 5000

export interface LoginDialogProps {
  open: boolean
  onOpenChange: (open: boolean) => void
  onLoginSuccess?: () => void
  onLoginFailed?: () => void
}

export const LoginDialog = ({ open, onOpenChange, onLoginSuccess, onLoginFailed }: LoginDialogProps) => {
  const loginWithTicket = useLoginStore((s) => s.loginWithTicket)
  const iframeRef = useRef<HTMLIFrameElement>(null)
  const [iframeLoadFailed, setIframeLoadFailed] = useState(false)
  const loadTimeoutRef = useRef<ReturnType<typeof setTimeout> | null>(null)
  const [isMobile, setIsMobile] = useState(false)

  const iframeUrl = isMobile ? IFRAME_URL : IFRAME_URL_VX

  const onSuccessRef = useRef(onLoginSuccess)
  const onFailedRef = useRef(onLoginFailed)
  useEffect(() => {
    onSuccessRef.current = onLoginSuccess
    onFailedRef.current = onLoginFailed
  }, [onLoginSuccess, onLoginFailed])

  const handleMessage = useCallback(async (event: MessageEvent) => {
    if (event.origin !== ALLOWED_ORIGIN) return
    if (!event.data?.action) return

    try {
      const data = typeof event.data === 'string' ? JSON.parse(event.data) : event.data
      if (data?.action === 'ticketSend' && data?.data?.ticket) {
        const ticket = data.data.ticket as string
        const req = await loginWithTicket(ticket)
        if (req?.success) {
          onSuccessRef.current?.()
        } else {
          toast.error(req?.message || '登录失败')
          onFailedRef.current?.()
        }
      }
    } catch {
      onFailedRef.current?.()
    }
  }, [loginWithTicket])

  useEffect(() => {
    if (!open) return
    setIsMobile(isMobileDevice())
    window.addEventListener('message', handleMessage)
    setIframeLoadFailed(false)

    loadTimeoutRef.current = setTimeout(() => {
      const iframe = iframeRef.current
      if (iframe) {
        try {
          const iframeDoc = iframe.contentDocument ?? iframe.contentWindow?.document
          if (!iframeDoc?.body || iframeDoc.body.children.length === 0) {
            setIframeLoadFailed(true)
          }
        } catch {
          setIframeLoadFailed(true)
        }
      }
    }, LOAD_TIMEOUT_MS)

    return () => {
      window.removeEventListener('message', handleMessage)
      if (loadTimeoutRef.current) {
        clearTimeout(loadTimeoutRef.current)
        loadTimeoutRef.current = null
      }
    }
  }, [open, handleMessage])

  const handleIframeLoad = useCallback(() => {
    if (loadTimeoutRef.current) {
      clearTimeout(loadTimeoutRef.current)
      loadTimeoutRef.current = null
    }
    setIframeLoadFailed(false)
  }, [])

  const handleIframeError = useCallback(() => {
    setIframeLoadFailed(true)
    if (loadTimeoutRef.current) {
      clearTimeout(loadTimeoutRef.current)
      loadTimeoutRef.current = null
    }
  }, [])

  const handleRetry = useCallback(() => {
    setIframeLoadFailed(false)
  }, [])

  const preventClose = useCallback((e: Event) => {
    e.preventDefault()
  }, [])

  return (
    <Dialog open={open} onOpenChange={onOpenChange}>
      <DialogContent
        showCloseButton
        className={cn(
          'gap-0 overflow-hidden boom_claw_login_dialog  p-0',
          isMobile ? 
          'w-[650px] max-w-[calc(100vw-2rem)] h-240 max-h-[calc(100dvh-1rem)]' 
          : 'w-[calc(1220px+32px*2)] max-w-[calc(100%-2rem)] ',
        )}
        onInteractOutside={preventClose}
        onEscapeKeyDown={preventClose}
      >
        <VisuallyHidden>
          <DialogTitle>登录</DialogTitle>
        </VisuallyHidden>
        <div
          className={cn(
            'relative overflow-hidden w-full',
            isMobile && 'h-240 max-h-[calc(100dvh-1rem)]',
            !isMobile && 'h-200 max-h-[calc(100dvh-2rem)]'
          )}
        >
          {!iframeLoadFailed ? (
            <iframe
              ref={iframeRef}
              src={iframeUrl}
              title="登录"
              sandbox="allow-same-origin allow-scripts allow-popups allow-forms"
              allow="camera; microphone"
              className="h-full w-full border-0 boom_claw_login_iframe"
              onLoad={handleIframeLoad}
              onError={handleIframeError}
            />
          ) : (
            <div className="flex h-full w-full flex-col items-center justify-center rounded border border-gray-200 bg-gray-50 px-4">
              <div className="mb-2 text-center text-lg text-gray-500">无法加载登录页面</div>
              <div className="mb-4 text-center text-sm text-gray-500">请检查网络连接或稍后重试</div>
              <Button
                role="button"
                tabIndex={0}
                className="cursor-pointer rounded  px-4 py-2 text-white "
                onClick={handleRetry}
                onKeyDown={(e) => e.key === 'Enter' && handleRetry()}
              >
                重新加载
              </Button>
            </div>
          )}
        </div>
      </DialogContent>
    </Dialog>
  )
}
