// src/vue/views/script-editor-vue/components/ScriptCharacterCard.vue
<script setup lang="ts">
import { ref, computed } from "vue";
import { ElMessage } from "element-plus";
import FEMALE from "@/assets/images/quick_creation/character_woman_sex.svg";
import MALE from "@/assets/images/quick_creation/character_man_sex.svg";
import CUSTOMSEX from "@/assets/images/quick_creation/character_custom_sex.svg";
import EditIcon from "@/assets/images/quick_creation/edit.svg";
import { addNote } from "@/api/notes";
import type { NoteSourceType, ScriptCharacterCardData } from "@/vue/utils/interfaces";


interface Props {
  data?: ScriptCharacterCardData;
  /** 剧本模式：使用此结构时展示 name / definition / age / personality / biography */
  showEdit?: boolean;
  /** 是否展示删除图标（未锁定时且有角色名时由父组件传入） */
  showDelete?: boolean;
  isCustom?: boolean; // 是否为自定义卡片
  loading?: boolean; // 是否显示加载状态
  isSelected?: boolean; // 是否被选中
  /** 编辑区右侧紧凑展示：标签行只显示第一个标签 + "...."，无渐变遮罩 */
  compactTags?: boolean;
}

interface Emits {
  (e: "click", event?: MouseEvent): void;
  (e: "edit", event: MouseEvent): void;
  (e: "delete", event: MouseEvent): void;
}

const props = withDefaults(defineProps<Props>(), {
  showEdit: false,
  showDelete: false,
  isCustom: false,
  loading: false,
  isSelected: false,
  compactTags: false,
});

const emit = defineEmits<Emits>();

const isCardHovered = ref(false);

// 根据 definition 是否包含「女」选图：含女用 MALE，否则 FEMALE（按需求说明）
const genderImage = computed(() =>
  props.data?.definition?.includes("女") ? FEMALE : MALE
);

// personality 按 、 切割为标签数组
const personalityTags = computed(() => {
  const s = props.data?.personality?.trim();
  if (!s) return [];
  return s.split(/[、,，]/).map((t) => t.trim()).filter(Boolean);
});

const handleClick = (event?: MouseEvent) => {
  // 点击卡片：由父组件决定是选中还是直接打开编辑（正常卡片区不展示选中态，直接打开编辑区）
  emit("click", event);
};

const handleEdit = (e: MouseEvent) => {
  e.stopPropagation();
  emit("edit", e);
};

const handleDelete = (e: MouseEvent) => {
  e.stopPropagation();
  emit("delete", e);
};

// 添加笔记（剧本卡片：name / definition / age / personality / biography）
const handleAddNote = async (e: MouseEvent) => {
  e.stopPropagation();
  if (!props.data?.name) {
    ElMessage.warning("角色信息不完整，无法添加笔记");
    return;
  }
  const parts: string[] = [];
  if (props.data.definition) parts.push(`身份：${props.data.definition}`);
  if (props.data.age) parts.push(props.data.age);
  if (props.data.personality) parts.push(props.data.personality);
  if (props.data.biography) parts.push(props.data.biography);
  const content = parts.join("\n\n");
  if (!content) {
    ElMessage.warning("角色内容为空，无法添加笔记");
    return;
  }
  try {
    await addNote(props.data.name, content, "PC_ADD" as NoteSourceType);
    ElMessage.success("笔记添加成功");
  } catch (error) {
    console.error("添加笔记失败:", error);
    ElMessage.error("添加笔记失败，请重试");
  }
};
</script>

<template>
  <!-- 自定义卡片 -->
  <div v-if="isCustom" class="quick-character-card custom-card" @click="handleClick">
    <!-- 背景图片 -->
    <div class="character-gender-bg custom-bg">
      <img :src="CUSTOMSEX" alt="" />
    </div>

    <!-- 内容 -->
    <div class="character-content custom-content">
      <div class="custom-text">自定义角色</div>
      <div class="custom-icon">
        <div class="plus-circle">
          <div class="plus-horizontal"></div>
          <div class="plus-vertical"></div>
        </div>
      </div>
    </div>
  </div>

  <!-- 角色卡片 -->
  <div v-else class="quick-character-card" @click="handleClick"
    @mouseenter="isCardHovered = true" @mouseleave="isCardHovered = false">
    <!-- 骨架图加载状态 -->
    <el-skeleton v-if="props.loading || !props.data?.name" class="character-card-skeleton" animated>
      <template #template>
        <el-skeleton-item variant="rect" style="height: 42px;" />
        <el-skeleton-item variant="rect" style="height: 28px;" />
        <el-skeleton-item variant="rect" style="height: 90px;" />
        <el-skeleton-item variant="rect" style="height: 40px;" />
      </template>
    </el-skeleton>

    <!-- 内容区域：设计稿 413-19008 四行布局 -->
    <template v-else>
      <div class="character-gender-bg">
        <img :src="genderImage" alt="" />
      </div>

      <div class="character-content">
        <!-- 第一行：姓名（单行...）+ 右上角 添加笔记、编辑（小号绝对定位） -->
        <div class="row-name">
          <div class="character-name" :title="props.data?.name">{{ props.data?.name }}</div>
          <div v-if="isCardHovered" class="header-actions">
            <span class="add-note-btn" @click="handleAddNote">添加笔记</span>
            <span v-if="showEdit" class="edit-btn" @click="handleEdit">
              <!-- <img :src="EditIcon" alt="编辑" class="edit-icon" /> -->
              编辑
            </span>
            <span v-if="showDelete" class="delete-btn" @click="handleDelete" title="删除角色">删除</span>
          </div>
        </div>

        <!-- 第二行：左右布局 definition | age，单行过长... -->
        <div class="row-definition-age">
          <div class="definition-text" :title="props.data?.definition">{{ props.data?.definition }}</div>
          <div class="age-text" :title="props.data?.age">{{ props.data?.age }}</div>
        </div>

        <!-- 第三行：personality 标签。紧凑模式（编辑区右侧）仅展示第一项+....；否则单行超出隐藏+右侧渐变省略 -->
        <div class="row-tags" :class="{ 'row-tags-compact': compactTags }">
          <div v-if="compactTags" class="tags-inner tags-inner-compact">
            <span v-if="personalityTags[0]" class="character-tag">{{ personalityTags[0] }}</span>
            <span class="tags-ellipsis">...</span>
          </div>
          <div v-else class="tags-inner">
            <span v-for="(tag, i) in personalityTags" :key="i" class="character-tag">{{ tag }}</span>
          </div>
        </div>

        <!-- 第四行：biography 多行可滚动，自上而下透明度渐变 -->
        <div class="row-biography">
          <div class="biography-mask"></div>
          <div class="biography-text">{{ props.data?.biography }}</div>
        </div>
      </div>
    </template>
  </div>
</template>

<style scoped lang="less">
.quick-character-card {
  width: 100%;
  height: 100%;
  padding: 20px 20px 20px 20px;
  background: #fff8e5;
  border-radius: 10px;
  box-shadow: 5px 5px 5px 0px rgba(58, 37, 0, 0.15);
  box-sizing: border-box;
  position: relative;
  cursor: pointer;
  overflow: hidden;
  display: flex;
  flex-direction: column;
  min-height: 0;

  .character-gender-bg {
    position: absolute;
    right: -20px;
    bottom: -20px;
    width: 167px;
    height: 175px;
    pointer-events: none;
    z-index: 0;

    img {
      width: 100%;
      height: 100%;
      object-fit: contain;
    }
  }

  .character-content {
    display: flex;
    flex-direction: column;
    gap: 15px;
    position: relative;
    z-index: 1;
    flex: 1;
    min-height: 0;
  }

  /* 第一行：姓名单行... + 右上角 添加笔记、编辑（小号绝对定位） */
  .row-name {
    position: relative;
    flex-shrink: 0;
    // height: 42px;
    min-width: 0;

    .character-name {
      font-size: 20px;
      font-weight: 700;
      line-height: 1.32;
      letter-spacing: 0.04em;
      color: #464646;
      // padding-right: 75px; /* 留给右上角按钮 */
      overflow: hidden;
      text-overflow: ellipsis;
      white-space: nowrap;
      display: block;
    }

    .header-actions {
      position: absolute;
      top: -15px;
      right: -15px;
      display: flex;
      align-items: center;
      gap: 4px;
      font-size: 12px;
      color: #999999;

      .add-note-btn,
      .edit-btn {
        cursor: pointer;
        white-space: nowrap;
        display: inline-flex;
        align-items: center;
      }
      .edit-btn {
        gap: 2px;
      }
      .edit-icon {
        width: 12px;
        height: 12px;
      }
      .add-note-btn:hover,
      .edit-btn:hover {
        color: var(--bg-editor-save);
      }
      .delete-btn {
        display: inline-flex;
        align-items: center;
        cursor: pointer;
        color: #999999;
        transition: color 0.2s;
      }
      .delete-btn:hover {
        color: #f56c6c;
      }
    }
  }

  /* 第二行：definition 左 | age 右，单行... */
  .row-definition-age {
    display: flex;
    flex-direction: row;
    justify-content: space-between;
    align-items: center;
    gap: 12px;
    flex-shrink: 0;
    min-width: 0;

    .definition-text {
      flex: 1;
      min-width: 0;
      font-size: 14px;
      font-weight: 400;
      line-height: 1.32;
      color: #464646;
      overflow: hidden;
      text-overflow: ellipsis;
      white-space: nowrap;
    }
    .age-text {
      flex-shrink: 0;
      font-size: 14px;
      font-weight: 400;
      line-height: 1.32;
      color: #464646;
      overflow: hidden;
      text-overflow: ellipsis;
      white-space: nowrap;
      max-width: 80px;
      text-align: right;
    }
  }

  /* 第三行：personality 标签 */
  .row-tags {
    flex-shrink: 0;
    position: relative;
    min-width: 0;
    width: 100%;
    overflow: hidden;

    .tags-inner {
      display: flex;
      flex-direction: row;
      flex-wrap: nowrap;
      gap: 5px;
      overflow: hidden;
      min-width: 0;
    }

    .tags-inner-compact {
      overflow: visible;
      align-items: center;
    }

    .tags-ellipsis {
      font-size: 13px;
      font-weight: 400;
      line-height: 1.32;
      color: #8a8a8a;
      margin-left: 4px;
      flex-shrink: 0;
    }

    .character-tag {
      flex-shrink: 0;
      padding: 6px 12px;
      border-radius: 21px;
      background: rgba(239, 175, 0, 0.2);
      font-size: 13px;
      font-weight: 400;
      line-height: 1.32;
      color: #4d4d4d;
      white-space: nowrap;
    }

    /* 非紧凑模式：右侧渐变遮罩 + 省略号（仅主列表生效，编辑区右侧不显示） */
    &:not(.row-tags-compact)::after {
      content: '';
      position: absolute;
      right: 0;
      top: 0;
      height: 100%;
      width: 8%;
      // transform: translateY(-50%);
      // padding: 6px 4px 6px 14px;
      background: linear-gradient(to right, transparent 0%, rgba(255, 248, 229, 0.4) 20%, rgba(255, 248, 229, 0.95) 100%);
      font-size: 12px;
      font-weight: 400;
      line-height: 1.32;
      color: #8a8a8a;
      pointer-events: none;
      // min-width: 32px;
      text-align: right;
    }
  }

  /* 第四行：biography 多行可滚动，自上而下透明度渐变 */
  .row-biography {
    flex: 1;
    min-height: 80px; /* 保证有可滚动区域 */
    position: relative;
    overflow: hidden;
    display: flex;
    flex-direction: column;

    .biography-mask {
      position: absolute;
      left: 0;
      right: 0;
      bottom: 0;
      height: 48px;
      background: linear-gradient(180deg, rgba(255, 248, 229, 0) 0%, rgba(255, 248, 229, 1) 100%);
      pointer-events: none;
      z-index: 1;
    }

    .biography-text {
      flex: 1;
      min-height: 0;
      width: 100%;
      overflow-y: auto;
      overflow-x: hidden;
      font-size: 14px;
      font-weight: 400;
      line-height: 1.32;
      letter-spacing: 0.04em;
      color: #464646;
      text-align: justify;
      padding-right: 6px;
      box-sizing: border-box;
      padding-bottom: 20px;
      -webkit-mask-image: linear-gradient(180deg, #000 0%, #000 70%, transparent 100%);
      mask-image: linear-gradient(180deg, #000 0%, #000 70%, transparent 100%);

      &::-webkit-scrollbar {
        width: 4px;
      }
      &::-webkit-scrollbar-thumb {
        background: rgba(0, 0, 0, 0.2);
        border-radius: 4px;
      }
    }
  }

  // 自定义卡片：文字与图标随窗口/卡片尺寸缩放，避免被截断
  &.custom-card {
    background: transparent;
    border: 2px dashed #d9d9d9;
    border-radius: 12px;
    box-shadow: 0px 0px 25px 0px rgba(58, 37, 0, 0.15);
    padding: 8%;
    transition: border-color 0.3s ease;
    outline: none !important;
    overflow: hidden;

    &:hover {
      border-color: var(--theme-color, rgba(239, 175, 0, 1));
      border-style: dashed;
      outline: none !important;
    }

    .custom-bg {
      right: -15%;
      bottom: -15%;
      width: min(180px, 65%);
      height: min(190px, 65%);
      opacity: 0.6;
    }

    .custom-content {
      display: flex;
      flex-direction: column;
      align-items: center;
      justify-content: center;
      flex: 1;
      min-height: 0;
      box-sizing: border-box;
      gap: 0;
    }

    .custom-text {
      font-size: clamp(14px, 2.8vmin, 28px);
      font-weight: 700;
      line-height: 1.32;
      letter-spacing: 0.04em;
      color: #d9d9d9;
      text-align: center;
      word-break: keep-all;
      padding: 0 4px;
      flex-shrink: 0;
      max-width: 100%;
      margin-bottom: 12px; /* 与下方加号图标间距 */
    }

    /* 加号容器：固定宽高比 1:1，避免变形 */
    .custom-icon {
      display: flex;
      align-items: center;
      justify-content: center;
      flex-shrink: 0;
      width: min(72px, 28%);
      aspect-ratio: 1;
      max-width: 72px;
      max-height: 72px;
    }

    .plus-circle {
      position: relative;
      width: 100%;
      height: 100%;
      aspect-ratio: 1;
      border: 2px solid #c8c8c8;
      border-radius: 50%;
      display: flex;
      align-items: center;
      justify-content: center;
      flex-shrink: 0;
    }

    .plus-horizontal {
      position: absolute;
      width: 50%;
      height: 0;
      border-top: 2px solid #c8c8c8;
      left: 50%;
      transform: translateX(-50%);
    }

    .plus-vertical {
      position: absolute;
      width: 0;
      height: 50%;
      border-left: 2px solid #c8c8c8;
      top: 50%;
      transform: translateY(-50%);
    }
  }
}

.character-card-skeleton {
  width: 100%;
  height: 100%; // 与父容器高度一致（380px）
  display: flex;
  flex-direction: column;
  justify-content: space-around;
  align-items: center;
  // padding: clamp(18px, 1.8vw, 26px); // 与卡片padding保持一致
  box-sizing: border-box;
  position: relative;
  z-index: 1;

  :deep(.el-skeleton__item) {
    background: linear-gradient(90deg, #f2f2f2 25%, #e6e6e6 50%, #f2f2f2 75%);
    background-size: 400% 100%;
    border-radius: 4px;
    width: 100%;
  }
}
</style>

// src/pages/script-editor/components/ScriptCharacterCard.tsx
import { useMemo, useState } from 'react'
import { addNote, type NoteSourceType } from '@/api/notes'
import { Skeleton } from '@/components/ui/Skeleton'
import { cn } from '@/lib/utils'
import { toast } from 'sonner'
import FEMALE from '@/assets/images/quick_creation/character_woman_sex.svg'
import MALE from '@/assets/images/quick_creation/character_man_sex.svg'
import CUSTOMSEX from '@/assets/images/quick_creation/character_custom_sex.svg'

export interface ScriptCharacterCardData {
  name?: string
  definition?: string
  age?: string
  personality?: string
  biography?: string
}

export interface ScriptCharacterCardProps {
  data?: ScriptCharacterCardData
  showEdit?: boolean
  showDelete?: boolean
  isCustom?: boolean
  loading?: boolean
  isSelected?: boolean
  compactTags?: boolean
  onClick?: (event?: React.MouseEvent<HTMLDivElement>) => void
  onEdit?: (event: React.MouseEvent) => void
  onDelete?: (event: React.MouseEvent) => void
}

export const ScriptCharacterCard = ({
  data,
  showEdit = false,
  showDelete = false,
  isCustom = false,
  loading = false,
  isSelected = false,
  compactTags = false,
  onClick,
  onEdit,
  onDelete,
}: ScriptCharacterCardProps) => {
  const [isCardHovered, setIsCardHovered] = useState(false)

  // 与 Vue 保持一致：definition 包含“女”时使用女性底图，否则男性底图
  const genderImage = useMemo(
    () => (data?.definition?.includes('女') ? FEMALE : MALE),
    [data?.definition]
  )

  const personalityTags = useMemo(() => {
    const raw = data?.personality?.trim()
    if (!raw) return []
    return raw
      .split(/[、,，]/)
      .map((tag) => tag.trim())
      .filter(Boolean)
  }, [data?.personality])

  const handleAddNote = async (e: React.MouseEvent) => {
    e.stopPropagation()
    if (!data?.name) {
      toast.warning('角色信息不完整，无法添加笔记')
      return
    }

    const parts: string[] = []
    if (data.definition) parts.push(`身份：${data.definition}`)
    if (data.age) parts.push(data.age)
    if (data.personality) parts.push(data.personality)
    if (data.biography) parts.push(data.biography)

    const content = parts.join('\n\n')
    if (!content) {
      toast.warning('角色内容为空，无法添加笔记')
      return
    }

    try {
      await addNote(data.name, content, 'PC_ADD' as NoteSourceType)
      toast.success('笔记添加成功')
    } catch (error) {
      console.error('添加笔记失败:', error)
      toast.error('添加笔记失败，请重试')
    }
  }

  if (isCustom) {
    return (
      <div
        role="button"
        className="relative flex size-full min-h-0 cursor-pointer flex-col overflow-hidden rounded-[12px] border-2 border-dashed border-[#d9d9d9] bg-transparent p-[8%] shadow-[0_0_25px_0_rgba(58,37,0,0.15)] outline-none transition-colors hover:border-(--theme-color)"
        onClick={onClick}
      >
        <div className="pointer-events-none absolute right-[-15%] bottom-[-15%] h-[min(190px,65%)] w-[min(180px,65%)] opacity-60">
          <img src={CUSTOMSEX} alt="" className="size-full object-contain" />
        </div>

        <div className="relative z-10 flex flex-1 flex-col items-center justify-center">
          <div className="mb-3 max-w-full shrink-0 px-1 text-center text-[clamp(14px,2.8vmin,28px)] font-bold leading-[1.32] tracking-[0.04em] text-[#d9d9d9]">
            自定义角色
          </div>

          <div className="flex h-[min(72px,28%)] w-[min(72px,28%)] max-h-[72px] max-w-[72px] shrink-0 items-center justify-center">
            <div className="relative size-full rounded-full border-2 border-[#c8c8c8] h-[33px]">
              <span className="absolute top-1/2 left-1/2 h-[2px] w-1/2 -translate-x-1/2 -translate-y-1/2 bg-[#c8c8c8]" />
              <span className="absolute top-1/2 left-1/2 h-1/2 w-[2px] -translate-x-1/2 -translate-y-1/2 bg-[#c8c8c8]" />
            </div>
          </div>
        </div>
      </div>
    )
  }

  const showSkeleton = loading || !data?.name

  return (
    <div
      role="button"
      className={cn(
        'relative flex size-full min-h-0 cursor-pointer flex-col overflow-hidden rounded-[10px] bg-[#fff8e5] p-5 shadow-[5px_5px_5px_0_rgba(58,37,0,0.15)]',
        isSelected && 'ring-2 ring-(--theme-color)'
      )}
      onClick={onClick}
      onMouseEnter={() => setIsCardHovered(true)}
      onMouseLeave={() => setIsCardHovered(false)}
    >
      {showSkeleton ? (
        <div className="relative z-10 flex size-full flex-col justify-around">
          <Skeleton className="h-[42px] w-full rounded-[4px]" />
          <Skeleton className="h-[28px] w-full rounded-[4px]" />
          <Skeleton className="h-[90px] w-full rounded-[4px]" />
          <Skeleton className="h-[40px] w-full rounded-[4px]" />
        </div>
      ) : (
        <>
          <div className="pointer-events-none absolute right-[-20px] bottom-[-20px] z-0 h-[175px] w-[167px]">
            <img src={genderImage} alt="" className="size-full object-contain" />
          </div>

          <div className="relative z-10 flex min-h-0 flex-1 flex-col gap-[15px]">
            <div className="relative min-w-0 shrink-0">
              <div
                className="truncate text-[20px] leading-[1.32] font-bold tracking-[0.04em] text-[#464646]"
                title={data?.name}
              >
                {data?.name}
              </div>

              {isCardHovered ? (
                <div className="absolute top-[-15px] right-[-15px] flex items-center gap-1 text-xs text-[#999999]">
                  <span
                    className="inline-flex cursor-pointer items-center whitespace-nowrap text-xs text-[#999999] hover:text-(--theme-color)"
                    onClick={handleAddNote}
                  >
                    添加笔记
                  </span>
                  {showEdit ? (
                    <span
                      className="inline-flex cursor-pointer items-center whitespace-nowrap text-xs text-[#999999] hover:text-(--theme-color)"
                      onClick={(e) => {
                        e.stopPropagation()
                        onEdit?.(e)
                      }}
                    >
                      编辑
                    </span>
                  ) : null}
                  {showDelete ? (
                    <span
                      className="inline-flex cursor-pointer items-center text-xs text-[#999999] transition-colors hover:text-[#f56c6c]"
                      onClick={(e) => {
                        e.stopPropagation()
                        onDelete?.(e)
                      }}
                    >
                      删除
                    </span>
                  ) : null}
                </div>
              ) : null}
            </div>

            <div className="flex min-w-0 shrink-0 items-center justify-between gap-3">
              <div
                className="flex-1 truncate text-sm leading-[1.32] text-[#464646]"
                title={data?.definition}
              >
                {data?.definition}
              </div>
              <div
                className="max-w-[80px] shrink-0 truncate text-right text-sm leading-[1.32] text-[#464646]"
                title={data?.age}
              >
                {data?.age}
              </div>
            </div>

            <div className={cn('relative w-full min-w-0 shrink-0 overflow-hidden', compactTags && 'pr-0')}>
              {compactTags ? (
                <div className="flex items-center gap-[5px]">
                  {personalityTags[0] ? (
                    <span className="shrink-0 rounded-[21px] bg-[rgba(239,175,0,0.2)] px-3 py-1.5 text-[13px] leading-[1.32] text-[#4d4d4d]">
                      {personalityTags[0]}
                    </span>
                  ) : null}
                  <span className="ml-1 shrink-0 text-[13px] leading-[1.32] text-[#8a8a8a]">...</span>
                </div>
              ) : (
                <>
                  <div className="flex min-w-0 flex-nowrap gap-[5px] overflow-hidden">
                    {personalityTags.map((tag, index) => (
                      <span
                        key={`${tag}-${index}`}
                        className="shrink-0 whitespace-nowrap rounded-[21px] bg-[rgba(239,175,0,0.2)] px-3 py-1.5 text-[13px] leading-[1.32] text-[#4d4d4d]"
                      >
                        {tag}
                      </span>
                    ))}
                  </div>
                  <div className="pointer-events-none absolute top-0 right-0 h-full w-[8%] bg-[linear-gradient(to_right,transparent_0%,rgba(255,248,229,0.4)_20%,rgba(255,248,229,0.95)_100%)]" />
                </>
              )}
            </div>

            <div className="relative flex min-h-[80px] flex-1 flex-col overflow-hidden">
              <div className="pointer-events-none absolute right-0 bottom-0 left-0 z-10 h-12 bg-[linear-gradient(180deg,rgba(255,248,229,0)_0%,rgba(255,248,229,1)_100%)]" />
              <div className="min-h-0 flex-1 overflow-y-auto overflow-x-hidden [scrollbar-width:thin]">
                <div
                  className="w-full pr-1.5 pb-5 text-justify text-sm leading-[1.32] tracking-[0.04em] text-[#464646]"
                  style={{
                    WebkitMaskImage:
                      'linear-gradient(180deg, #000 0%, #000 70%, transparent 100%)',
                    maskImage:
                      'linear-gradient(180deg, #000 0%, #000 70%, transparent 100%)',
                  }}
                >
                  {data?.biography}
                </div>
              </div>
            </div>
          </div>
        </>
      )}
    </div>
  )
}
